manage_system_demo/manage_system_demo/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

from manage_app.views import depart, user, num, admin, account, task, order, char, upload, city

urlpatterns = [
    # path("admin/", admin.site.urls),
    # media 存放路径
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('add/depart/', depart.add_depart),
    path('delete/depart/', depart.delete_depart),
    path('edit/<int:nid>/depart/', depart.edit_depart),
    path('depart/multi/', depart.depart_multi),

    # 用户管理
    path('user/list/', user.user_list),
    path('add/user/', user.add_user),
    path('delete/user/', user.delete_user),
    path('edit/<int:nid>/user/', user.edit_user),

    # 靓号管理
    path('num/list/', num.num_list),
    path('add/num/', num.add_num),
    path('delete/<int:nid>/num/', num.delete_num),
    path('edit/<int:nid>/num/', num.edit_num),

    # 管理员
    path('admin/list/', admin.admin_list),
    path('add/admin/', admin.admin_add),
    path('delete/<int:nid>/admin/', admin.delete_admin),
    path('edit/<int:nid>/admin/', admin.edit_admin),
    path('reset/<int:nid>/admin/', admin.reset_admin),

    # 登录
    path('login/', account.account_login),
    path('logout/', account.account_logout),
    path('image/code/', account.image_code),

    # 用户管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('add/task/', task.add_task),

    # 订单管理
    path('order/list/', order.order_list),
    path('add/order/', order.add_order),
    path('delete/order/', order.delete_order),
    path('detail/order/', order.detail_order),
    path('edit/order/', order.edit_order),

    # 数据统计
    path('chars/list/', char.char_list),
    path('chars/bar/', char.char_bar),
    path('chars/pie/', char.char_pie),
    path('chars/line/', char.char_line),

    # 文件上传
    path('upload/file/', upload.upload_file),
    path('upload/form/', upload.upload_form),
    path('upload/modelform/', upload.upload_model_form),

    # 城市列表
    path('city/list/', city.city_list),
    path('add/city/', city.add_city),
]

manage_system_demo/manage_app/models.py
from django.db import models


# Create your models here.
class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="标题", max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2,
                                  default=0)  # max_digits 数字长度， decimal_places 小数位数
    creta_time = models.DateField(verbose_name="入职时间")
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE)
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)

    def __str__(self):
        return self.name


class PrettyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(max_length=32, verbose_name="手机号")
    # 想要允许为空 null=True, blank=True
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="价值", default=0)
    level_choices = (
        (1, 'Lv1'),
        (2, 'Lv2'),
        (3, 'Lv3'),
        (4, 'Lv4')
    )
    level = models.SmallIntegerField(verbose_name="等级", choices=level_choices, default=1)
    status_choices = (
        (1, "占用"),
        (2, "未占用")
    )
    status = models.SmallIntegerField(verbose_name="占用状态", choices=status_choices, default=2)


class Admin(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)


class Task(models.Model):
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时")
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="任务详请", max_length=64)
    user = models.ForeignKey(verbose_name="负责人", to=UserInfo, to_field="id", on_delete=models.CASCADE)


class Order(models.Model):
    """订单"""
    oid = models.CharField(verbose_name="订单号", max_length=64, null=False, blank=False)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="价格")
    status_choices = (
        (1, "已售"),
        (2, "未售")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    user = models.ForeignKey(verbose_name="负责人", to=UserInfo, to_field="id", on_delete=models.CASCADE)


class Boss(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="图片", max_length=64)


class City(models.Model):
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")

    # FileField 本质上也是 CharField，使用 FileField 的好处是能自动保存到 upload_to 指定的文件夹，例如这里是 city/ ,实际保存到的路径是 media/city 文件夹下
    img = models.FileField(verbose_name="oLog", max_length=64, upload_to='city/')

manage_system_demo/manage_app/views/account.py
from django.shortcuts import render, HttpResponse, redirect

from manage_app import models
from manage_app.utils.form import LoginForm
from manage_app.utils.code import check_code


def account_login(request):
    """用户登录"""
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {"form": form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        user_input_code = form.cleaned_data.pop('code')
        admin_obj = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_obj:
            # 在指定输入框位置底部显示错误信息
            form.add_error("password", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})
        if user_input_code.upper() != str.upper(request.session.get("image_code", "")):
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {"form": form})
        # 生成cookie，并写入到session中
        request.session['info'] = {"id": admin_obj.id, "username": admin_obj.username}
        request.session.set_expiry(60*60*24*7)
        request.session.pop('image_code')
        return redirect('/admin/list/')
    return render(request, 'login.html', {"form": form})


def account_logout(request):
    request.session.clear()
    return redirect('/login/')


from io import BytesIO
def image_code(request):
    img, code_str = check_code()
    stream = BytesIO()
    img.save(stream, 'png')
    request.session['image_code'] = code_str
    request.session.set_expiry(60)
    return HttpResponse(stream.getvalue())

manage_system_demo/manage_app/views/admin.py
from django.shortcuts import render, redirect, HttpResponse
from manage_app import models

from manage_app.utils.pagination import Pagination
from manage_app.utils.form import AdminModel, AdminEditModel, AdminResetModel


def admin_list(request):
    """管理员列表"""
    info = request.session.get("info")
    if not info:
        return redirect("/account/login")

    data_dict = {}
    value = request.GET.get("q", "")
    if value:
        data_dict["username__contains"] = value
    queryset = models.Admin.objects.all(**data_dict)
    page_obj = Pagination(request, queryset, page_size=10)
    context = {
        "queryset": page_obj.page_queryset,
        "page_string": page_obj.html(),
        "value": value
    }
    return render(request, 'admin_list.html', context)


def admin_add(request):
    title = "添加管理员"
    if request.method == "GET":
        form = AdminModel()
        return render(request, 'change.html', {"form": form, "title": title})
    form = AdminModel(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {"form": form, "title": title})


def edit_admin(request, nid):
    raw_obj = models.Admin.objects.filter(id=nid).first()
    if not raw_obj:
        msg = "用户不存在"
        return render(request, 'error.html', {'msg': msg})

    title = "编辑管理员"
    if request.method == "GET":
        form = AdminEditModel(instance=raw_obj)
        return render(request, 'change.html', {"form": form, "title": title})
    form = AdminEditModel(request.POST, instance=raw_obj)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {"form": form, "title": title})


def delete_admin(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


def reset_admin(request, nid):
    title = "重置密码"
    obj = models.Admin.objects.filter(id=nid).first()
    if request.method == "GET":
        form = AdminResetModel(instance=obj)
        return render(request, 'change.html', {"form": form, "title": title})
    form = AdminResetModel(request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {"form": form, "title": title})

manage_system_demo/manage_app/views/char.py
import random
from django.shortcuts import render
from django.http import JsonResponse


def char_list(request):
    return render(request, 'char_list.html')


def char_bar(request):
    legend = ['销量1']
    data_list = [
        {
            "name": '销量1',
            "type": 'bar',
            "data": [51, 201, 361, 101, 101, 201]
        }
    ]
    type_list = ['衬衫1', '羊毛衫1', '雪纺衫1', '裤子1', '高跟鞋1', '袜子1']
    result = {
        "status": True,
        "data": {
            "legend": legend,
            "data_list": data_list,
            "type_list": type_list
        }
    }
    return JsonResponse(result)


def char_pie(request):
    data_list = [
        {"value": 104, "name": 'Search Engine'},
        {"value": 73, "name": 'Direct'},
        {"value": 58, "name": 'Email'},
        {"value": 48, "name": 'Union Ads'},
        {"value": 30, "name": 'Video Ads'}
    ]

    result = {
        "status": True,
        "data": {
            "data_list": data_list
        }
    }
    return JsonResponse(result)


def char_line(request):
    line_dict = {}
    data_list = ['Mon1', 'Tue2', 'Wed3', 'Thu4', 'Fri5', 'Sat6', 'Sun7']
    for i in range(5):
        line_dict[f"line{str(i + 1)}_data"] = [random.randint(1, 100) for i in range(7)]
    print(line_dict)

    result = {
        "status": True,
        "data": {
            "data_list": data_list,
            "line1_data": line_dict["line1_data"],
            "line2_data": line_dict["line2_data"],
            "line3_data": line_dict["line3_data"],
            "line4_data": line_dict["line4_data"],
            "line5_data": line_dict["line5_data"]
        }
    }
    return JsonResponse(result)

manage_system_demo/manage_app/views/city.py
from django.shortcuts import HttpResponse, redirect, render

from manage_app import models
from manage_app.utils.bootstrap import BootStrapModelForm


def city_list(request):
    if request.method == "GET":
        data_list = models.City.objects.all()
        return render(request, 'city_list.html', {"data_list": data_list})


class UpModelForm(BootStrapModelForm):
    bootstrap_exclude_fields = ['img']

    class Meta:
        model = models.City
        fields = "__all__"


def add_city(request):
    title = "ModelForm 文件上传"
    if request.method == "GET":
        form = UpModelForm()
        return render(request, 'upload_model_form.html', {"form": form, "title": title})
    form = UpModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/city/list/')
    return render(request, 'upload_model_form.html', {"form": form, "title": title})

manage_system_demo/manage_app/views/depart.py
from django.shortcuts import render, redirect, HttpResponse

from manage_app.models import *


def depart_list(request):
    """部门列表"""
    queryset = Department.objects.all()
    return render(request, 'depart_list.html', {'data_list': queryset})


def add_depart(request):
    """添加部门"""
    if request.method == "GET":
        return render(request, 'add_depart.html')
    data = request.POST
    title = data.get("title")
    Department.objects.create(title=title)
    return redirect('/depart/list/')


def delete_depart(request):
    """删除部门"""
    nid = request.GET.get("id")
    Department.objects.filter(id=nid).delete()
    return redirect('/depart/list')


def edit_depart(request, nid):
    """编辑部门"""
    if request.method == "GET":
        obj = Department.objects.filter(id=nid).first()
        return render(request, 'edit_depart.html', {"obj": obj})
    title = request.POST.get("title")
    Department.objects.filter(id=nid).update(title=title)
    return redirect('/depart/list/')


def depart_multi(request):
    from openpyxl import load_workbook

    # 1.获取文件对象
    file_obj = request.FILES.get("tfile")

    # 2.将对象传递给 openpyxl，由openpyxl读取文件内容
    wb = load_workbook(file_obj)
    # 2.1 读取第1个 sheet 的内容
    sheet = wb.worksheets[0]

    # 3.循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value
        exist = Department.objects.filter(title=text).exists()
        if not exist:
            Department.objects.create(title=text)

    return redirect('/depart/list/')

manage_system_demo/manage_app/views/num.py
from django.shortcuts import render, redirect, HttpResponse

from manage_app.utils.pagination import Pagination
from manage_app.utils.form import *
from manage_app.models import *


def num_list(request):
    data_dict = {}
    # request.GET.get("q", "")，第二个参数为key的值，比如这里是默认将q复制为""，如果不填，将会显示为None
    value = request.GET.get("q", "")
    if value:
        data_dict["mobile__contains"] = value

    queryset = PrettyNum.objects.filter(**data_dict).order_by("-level")
    page_object = Pagination(request, queryset)

    # 1.根据用户想要访问的页码，计算出起止位置
    # page = int(request.GET.get('page', 1))
    # page_size = 2
    # start = page * page_size - page_size
    # end = page * page_size

    # # 2.获取数据库筛选后的总条数
    # total_count = PrettyNum.objects.filter(**data_dict).order_by("-level").count()
    #
    # # 3.总页码
    # total_page_count, div = divmod(total_count, page_size)
    # if div:
    #     total_page_count += 1

    # 5.计算当前页的前x页和后x页，用于页码仅展示前 x 页 和 后 x页
    # plus = 2
    #
    # # 6.当前页面如果已经满足显示所有数据，则页码数量不再需要调整
    # if total_page_count <= 2 * plus + 1:
    #     start_page = 1
    #     end_page = total_page_count
    # else:
    #     if page <= plus:
    #         start_page = 1
    #         end_page = 2 * plus + 1
    #     else:
    #         if (page + plus) > total_page_count:
    #             start_page = total_page_count - 2 * plus
    #             end_page = total_page_count
    #         else:
    #             start_page = page - plus
    #             end_page = page + plus

    # # 4.生成前端页码代码
    # page_str_list = []
    #
    # # 首页
    # prev = f"<li><a href='?page={1}'>首页</a></li>"
    # page_str_list.append(prev)
    #
    # # 上一页
    # if page > 1:
    #     prev = f"<li><a href='?page={page-1}'>上一页</a></li>"
    # else:
    #     prev = f"<li><a href='?page={1}'>上一页</a></li>"
    # page_str_list.append(prev)
    #
    # for i in range(start_page, end_page + 1):
    #     if i == page:
    #         ele = f"<li class='active'><a href='?page={i}'>{i}</a></li>"
    #     else:
    #         ele = f"<li><a href='?page={i}'>{i}</a></li>"
    #     page_str_list.append(ele)
    #
    # # 下一页
    # if page < total_page_count:
    #     prev = f"<li><a href='?page={page+1}'>下一页</a></li>"
    # else:
    #     prev = f"<li><a href='?page={total_page_count}'>下一页</a></li>"
    # page_str_list.append(prev)
    #
    # # 尾页
    # prev = f"<li><a href='?page={total_page_count}'>尾页</a></li>"
    # page_str_list.append(prev)
    #
    # page_string = mark_safe("".join(page_str_list))

    context = {"data_list": page_object.page_queryset, "value": value, "page_string": page_object.html()}

    return render(request, 'num_list.html', context)


def add_num(request):
    if request.method == "GET":
        form = NumModel()
        return render(request, 'add_num.html', {"form": form})
    form = NumModel(request.POST)
    if form.is_valid():
        form.save()
        return redirect('/num/list/')
    return render(request, 'add_num.html', {'form': form})


def edit_num(request, nid):
    raw_obj = PrettyNum.objects.filter(id=nid).first()
    if request.method == "GET":
        form = NumEditModel(instance=raw_obj)
        return render(request, 'edit_num.html', {"form": form})
    form = NumEditModel(data=request.POST, instance=raw_obj)
    if form.is_valid():
        form.save()
        return redirect('/num/list/')
    return render(request, 'edit_num.html', {"form": form})


def delete_num(request, nid):
    PrettyNum.objects.filter(id=nid).delete()
    return redirect('/num/list/')

manage_system_demo/manage_app/templates/add_user.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default container">
        <div class="panel-heading">
            <h3 class="panel-title">用户添加</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">添加</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_creta_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'zh-CN',
                autoclose: true
            })
        })
    </script>
{% endblock %}

manage_system_demo/manage_app/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
        <a href="/add/admin/" class="btn btn-success">新建管理员</a>
        <div style="float: right;width: 300px">
            <form method="get">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..." name="q" value="{{ value }}">
                    <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go!</button>
                </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">管理员列表</div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>名字</th>
                <th>密码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.username }}</td>
                    <td>{{ obj.password }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/edit/{{ obj.id }}/admin/">
                            编辑
                        </a>
                        <a class="btn btn-danger btn-xs"
                           onclick="location.href='/delete/{{ obj.id }}/admin/'">
                            删除
                        </a>
                        <a class="btn btn-default btn-xs"
                           onclick="location.href='/reset/{{ obj.id }}/admin/'">
                            重置密码
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </nav>
{% endblock %}

manage_system_demo/manage_app/templates/change.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default container">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">添加</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_creta_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'zh-CN',
                autoclose: true
            })
        })
    </script>
{% endblock %}

manage_system_demo/manage_app/templates/city_list.html
{% extends 'layout.html' %}

{% block content %}

    <div style="margin-bottom: 10px">
        <a href="/add/city/" class="btn btn-success">添加城市</a>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">城市列表</div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Logo</th>
                <th>名称</th>
                <th>人口</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in data_list %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>
                        <img src="/media/{{ obj.img }}" style="height: 80px">
                    </td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.count }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

manage_system_demo/manage_app/templates/edit_depart.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default container">
    <div class="panel-heading">
        <h3 class="panel-title">部门编辑</h3>
    </div>
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>部门</label>
                <input type="text" placeholder="部门" name="title" style="width: 50%" value="{{ obj.title }}">
            </div>
            <button type="submit" class="btn btn-success">更新</button>
        </form>
    </div>
</div>
{% endblock %}

manage_system_demo/manage_app/templates/edit_num.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default container">
        <div class="panel-heading">
            <h3 class="panel-title">靓号编辑</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">添加</button>
            </form>
        </div>
    </div>
{% endblock %}

manage_system_demo/manage_app/templates/edit_user.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default container">
        <div class="panel-heading">
            <h3 class="panel-title">用户编辑</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">添加</button>
            </form>
        </div>
    </div>
{% endblock %}

manage_system_demo/manage_app/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="alert alert-danger" role="alert">{{ msg }}</div>
{% endblock %}

manage_system_demo/manage_app/templates/num_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px" class="clearfix">
        <a href="/add/num/" class="btn btn-success">靓号添加</a>
        <div style="float: right;width: 300px">
            <form method="get">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..." name="q" value="{{ value }}">
                    <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go!</button>
                </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">号码列表</div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>号码</th>
                <th>价值</th>
                <th>等级</th>
                <th>状态</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in data_list %}
                <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.mobile }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_level_display }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/edit/{{ obj.id }}/num/">
                            编辑
                        </a>
                        <a class="btn btn-danger btn-xs"
                           onclick="location.href='/delete/{{ obj.id }}/num/'">
                            删除
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </nav>
{% endblock %}

manage_system_demo/manage_app/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
        <a href="/add/user/" class="btn btn-success">新建用户</a>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">用户列表</div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>名字</th>
                <th>密码</th>
                <th>年龄</th>
                <th>账户余额</th>
                <th>入职时间</th>
                <th>性别</th>
                <th>部门</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.password }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.account }}</td>
                    <td>{{ obj.creta_time|date:"Y-m-d"}}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.depart.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/edit/{{ obj.id }}/user/">
                            编辑
                        </a>
                        <a class="btn btn-danger btn-xs"
                           onclick="location.href='/delete/user/?id={{ obj.id }}'">
                            删除
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </nav>
{% endblock %}